config/routes.rb
Rails.application.routes.draw do

  resources :tenants
  resources :rental_applications, except: [:edit, :update, :destroy]
  resources :apartments, only: [:index, :show]
  resources :neighborhoods, only: [:index, :show]
  resources :brokers, only: [:index, :show]
  

  root 'tenants#login'
  get 'welcome/index', to: 'welcome#index'
  
  get '/profile', to: 'tenants#profile', as: 'profile'

  # GET THE USER THE LOGIN FORM
  # get "/index", to: "tenants#index"
  get '/login', to: 'tenants#login', as: 'login'
  # HANDLE THE LOGIN FORM SUBMISSION
  post '/send_the_form_here', to: 'tenants#handle_login'
  delete '/logout', to: 'tenants#logout', as: 'logout'

  get '/rental_application/apartment/:apt_id', to: 'rental_applications#new_form', as: 'apartment_id'

end

app/models/apartment.rb
class Apartment < ApplicationRecord
  has_many :rental_applications
  has_many :tenants, through: :rental_applications
  belongs_to :broker
  belongs_to :neighborhood
  default_scope { order(rent_amount: :asc)}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/broker.rb
class Broker < ApplicationRecord
    has_many :apartments
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
    has_many :apartments
    default_scope { order(safety_level: :desc) }
end

app/models/rental_application.rb
class RentalApplication < ApplicationRecord
  belongs_to :tenant
  belongs_to :apartment

  # validates :description, length: {minimum: 20, maximum: 100}, presence: true
end

app/models/tenant.rb
class Tenant < ApplicationRecord
    has_many :rental_applications
    has_many :apartments, through: :rental_applications

    validates :name, presence: true, uniqueness: true
    validates :email_address, presence: true, uniqueness: true
    validates :age, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 21 }

    has_secure_password
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController

    # def index
    #     @apartments = Apartment.all
    # end

    def show
        @apartment = Apartment.find(params[:id])
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :check_if_tenant_is_logged_in?
    before_action :authorized_to_see_page

    def set_current_tenant
        @current_tenant = Tenant.find_by(id: session[:tenant_id])
    end

    def check_if_tenant_is_logged_in?
        !set_current_tenant.nil?
    end

    def authorized_to_see_page
        redirect_to login_path unless check_if_tenant_is_logged_in?
    end

end

app/controllers/brokers_controller.rb
class BrokersController < ApplicationController

    def index
        @brokers = Broker.all
    end

    def show
        @broker = Broker.find(params[:id])
        @apartments = Apartment.all
    end

end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController

    def index
        @neighborhoods = Neighborhood.all
    end

    def show
        @neighborhood = Neighborhood.find(params[:id])
    end
end

app/controllers/rental_applications_controller.rb
class RentalApplicationsController < ApplicationController

    def index
        @rental_applications = @current_tenant.rental_applications
    end

    def show
        @rental_application = RentalApplication.find(params[:id])
    end

    def new_form
        @apartment = Apartment.find(params[:apt_id])
        @rental_application = RentalApplication.new
    end

    def create
        @rental_application = @current_tenant.rental_applications.create(rental_app_params)
        redirect_to rental_applications_path
    end

    # def destroy
    #     @rental_application.destroy
    #     redirect_to rental_applications_path
    # end

    private

    def rental_app_params
        params.require(:rental_application).permit(:tenant_id, :apartment_id, :description)
    end

end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController

  before_action :get_tenant, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorized_to_see_page, only: [:login, :handle_login, :new, :create]

  def profile
    render :profile
  end

  def login
    @error = flash[:error]
  end

  def handle_login
    @tenant = Tenant.find_by(email_address: params[:email_address])
    if @tenant && @tenant.authenticate(params[:password])
      # If the tenant is found AND their password matches
      session[:tenant_id] = @tenant.id
      redirect_to welcome_index_path
    else
      flash[:error] = "Incorrect e-mail address or password"
      redirect_to login_path
    end
  end

  def logout
    session[:tenant_id] = nil
    redirect_to login_path
  end

  def new
    if check_if_tenant_is_logged_in?
      redirect_to welcome_index_path
    else
      @errors = flash[:errors]
      @tenant = Tenant.new
      render :new
    end
  end
  
  def create
    @tenant = Tenant.create(tenant_params)
    if @tenant.valid?
      session[:tenant_id] = @tenant.id
      redirect_to welcome_index_path
    else 
      flash[:errors] = @tenant.errors.full_messages
      redirect_to new_tenant_path
    end
    
  end

  def edit
    @tenant = @current_tenant
  end

  def update
    @tenant.update(tenant_params)
    redirect_to welcome_index_path
  end

  def destroy
    @tenant.destroy
    redirect_to login_path
  end

  private

  def get_tenant
    @tenant = Tenant.find(params[:id])
  end

  def tenant_params
    params.require(:tenant).permit(:name, :email_address, :age, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brokers_helper.rb
module BrokersHelper
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/helpers/rental_applications_helper.rb
module RentalApplicationsHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/apartments/show.html.erb
<h3> Address: <%= @apartment.address%> | Bed: <%= @apartment.bedroom_num %> | Bath: <%= @apartment.bathroom_num %> </h3>

app/views/brokers/index.html.erb
<h2> These are all the brokers </h2>
<ul>
<% @brokers.each do |broker| %>
    <li><%= link_to broker.name, broker_path(broker) %></li>
<% end %>

app/views/brokers/show.html.erb
<h2> These are the apartments for: <%= @broker.name %> </h2>
<% @broker.apartments.each do |brok| %>
    <li> <%= link_to brok.address %> </li>
<% end %>

app/views/layouts/application.html.erb
<div class="card bg-dark text-white">
  <img class="card-img" src="https://images.unsplash.com/photo-1594072702031-f0e2a602dd2c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80" alt="Card image">
  <div class="card-img-overlay">

      <% if check_if_tenant_is_logged_in? %>
        <nav>
          LOGGED IN: <%= @current_tenant.name %> 
          <%= button_to "LOG OUT", logout_path, :class => 'btn btn-outline-warning', method: :delete %>
        </nav>
      <% else %>
        <nav> 
          <%= link_to "LOGIN PAGE", login_path %>
        </nav>
      <% end %>
      <%= yield %>
  </div>
</div>

<!DOCTYPE html>
  <html>
    <head>
      <title>RentalApp</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
</html>

app/views/neighborhoods/index.html.erb
<h1>List of Neighborhoods</h1>
<ul>
    <% @neighborhoods.each do |neighborhood| %>
        <li> <%= link_to neighborhood.name, neighborhood_path(neighborhood) %> | Safety level: <%= neighborhood.safety_level %> </li><br>
    <% end %>
</ul>

app/views/neighborhoods/show.html.erb
<h2> These are the apartments for: <%= @neighborhood.name %> | Safety level: <%= @neighborhood.safety_level%> </h2>

<% @neighborhood.apartments.each do |apt| %>
    <li> <%= link_to apt.address, apartment_id_path(apt.id) %> - Bed: <%= apt.bedroom_num %> | Bath <%= apt.bathroom_num %> | Rent: $<%= apt.rent_amount %></li><br>
<% end %>

app/views/rental_applications/index.html.erb
<h1> My applications </h1>

<ul>
    <% @current_tenant.rental_applications.each do |rental_app| %>
        <li> <%= rental_app.apartment.address %> - $<%= rental_app.apartment.rent_amount %> <br > Description: <%= rental_app.description %></li>
    <% end %>
</ul>

<%= button_to "Main menu", welcome_index_path, :class => 'btn btn-outline-primary', method: :get %> <br/>

app/views/rental_applications/new_form.html.erb
<h2> Tell us why you are interested in this apartment:</h2>

<% if @errors %>
    <% @errors.each do |error|%>
        <div style="color:red"><%= error %></div>
    <% end %>
<% end %>

<%= form_for @rental_application do |f| %>
    <%= f.hidden_field :apartment_id, value: @apartment.id %>
    <%= f.label :description, "Description:"%><br>
    <%= f.text_area :description, cols: "40", rows: "7" %>
    <br>
    <br>
    <%= f.submit "Submit", ({:class => "btn btn-outline-primary"}) %>
<% end %>

app/views/tenants/edit.html.erb
<h1> Edit info of <%= @tenant.name %> </h1>

<%= form_for @tenant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %> <br/>
  <br>
  <%= f.label :email_address %>
  <%= f.text_field :email_address %><br/>
  <br>
  <%= f.submit({:class => "btn btn-outline-secondary"})%>
<% end %>

app/views/tenants/login.html.erb
<h1>Welcome To Homes  </h1>
<p> by Sayana & Samir </p>
<br>

<% if @error %>
    <p style= "color: red"> <%= @error %></p>
<% end %>

<%# THE FORM BELOW MAKES A POST REQUEST TO "/send_the_form_here" %>

<%= form_tag "/send_the_form_here" do %>
    <%= label_tag :email_address %>
    <%= text_field_tag :email_address %><br>
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <%= submit_tag "Login", :class => 'btn btn-primary' %>
    <p>If you don't have an account:  <%= link_to "Sign Up", new_tenant_path %></p>
<% end %>

app/views/tenants/new.html.erb
<h1> Create a profile </h1>

<% if @errors %>
  <% @errors.each do |error|%>
    <p style= "color: red"> <%= error %></p>
  <% end %>
<% end %>

<%= form_for @tenant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %> <br/>
  <br>
  <%= f.label :age %>
  <%= f.number_field :age %><br/>
  <br>
  <%= f.label :email_address %>
  <%= f.text_field :email_address %><br/>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %><br/>
  <br>
  <%= f.submit({:class => "btn btn-outline-primary btn-lg"}) %>
<% end %>

app/views/tenants/profile.html.erb
<h1>Your Profile</h1>

<h2>Name: <%= @current_tenant.name %> </h2>

<p> 
    <strong> Age:</strong> <%= @current_tenant.age %> years old 
</p>

<%= form_for @current_tenant do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> <br>
    <%= f.label :age %>
    <%= f.number_field :age %><br>
    <%= f.label :password %>
    <%= f.text_field :password%>
    <br>
    <%= f.submit "Update Info", ({:class => "btn btn-outline-secondary btn-sm"}) %>
<% end %> 
<br/>

<%= button_to "Delete profile", @current_tenant, :class => "btn btn-danger", :method => :delete %>

app/views/welcome/index.html.erb
<h1> Main Menu </h1>
<br>
<%= button_to "My Applications", rental_applications_path, :class => "btn btn-outline-info", method: :get %><br>
<%= button_to "Profile", profile_path, :class => "btn btn-outline-info", method: :get%><br>
<%= button_to "Create an application", neighborhoods_path, :class => "btn btn-outline-info", method: :get %> 